hiroki19990625/EngineGL

- EngineGL.Editor/EngineGL.Editor.csproj
- EngineGL.Editor/packages.config
- EngineGL/EngineGL.csproj
- EngineGL/Properties/AssemblyInfo.cs
> Native copy bug

- EngineGL/Structs/Math/Vec2.cs
- EngineGL/Structs/Math/Vec3.cs
Vecクラスのstatic変数は変更できてしまう問題があったので、readonlyにした。
Vecクラスの不要な演算子を削除。
Vecクラスにいくつかの汎用関数を追加した。
まあ、とりあえずウオーミングアップってことでやってみた。
> Vecクラスの修正と機能追加

- EngineGL.Tests/EngineGL.Tests.csproj
- EngineGL.Tests/Structs/Math/VecTests.cs
> Vecのテスト書いた

- EngineGL/EngineGL.csproj
- EngineGL/Impl/Game.cs
- EngineGL/Impl/SceneManager.cs
これはまだ、全然途中結果なのでリジェクトしてもらっても構わない。
こんな感じでGameクラスからScene部分を分離してみたけど、どうかな？
引数メッチャ長くなったがこれはいつか改善する
>  Gameクラスからシーン管理の処理を雑に分離

- EngineGL.Tests/Impl/GameTests.cs
- EngineGL/Core/IGame.cs
- EngineGL/EngineGL.csproj
- EngineGL/Impl/Game.cs
- EngineGL/Impl/SceneManager.cs
- EngineGL/Impl/SceneManagerEvents.cs
シーン系のイベントを全部クラスでまとめました。
SceneManagerEvents.csファイルの位置不適当だったかも・・・
シーンロード系のイベントって Object senderを受け取れるみたいだけど、必要ないのでは？（ダウンキャスト危険だし・・・）
C#のライブラリ設計したことないからわかんないけど・・・
>  SceneManagerのイベントをまとめた

- EngineGL/Impl/Game.cs
> GameクラスのLoggerをReadonlyにした

- EngineGL.Tests/Utils/ResultTests.cs
- EngineGL/Utils/Result.cs
> Resultクラスをより便利に

- EngineGL/Impl/DrawableList.cs
- EngineGL/Impl/Scene.cs
描画の順序を制御するための布石です。
今後は描画レイヤーをDrawableListに実装していきます。
多分、IDrawableのメソッドを新たに追加すると思う。
それが終わったらTransformあたりに親子関係の実装をしていく予定
> 描画制御するクラスを作ってSceneクラスから分離した

- EngineGL.Tests/Exec/TextObjects/TextureRender.cs
- EngineGL/Core/Resource/ITexture.cs
- EngineGL/Impl/Drawable/Shape2D/RawTexture2D.cs
- EngineGL/Impl/Resource/ResourceManager.cs
- EngineGL/Impl/Resource/Texture2D.cs
Reverts hiroki19990625/EngineGL#30
> Revert "TextureAPIをジェネリクス対応"

- EngineGL.Tests/EngineGL.Tests.csproj
- EngineGL.Tests/Exec/GamrExecTest.cs
- EngineGL.Tests/Exec/TestComponents/CameraComponent.cs
- EngineGL.Tests/Exec/TestComponents/RotateComponent.cs
- EngineGL.Tests/Exec/TestComponents/SolidBoxObject3DComponet.cs
- EngineGL/Impl/Drawable/Shape3D/SolidBoxObject3D.cs
> 3Dtest回転無理

- EngineGL.Tests/EngineGL.Tests.csproj
- EngineGL.Tests/Exec/NodeTest.cs
- EngineGL/Core/ITransform.cs
- EngineGL/Impl/Components/Transform.cs
なんか中心座標おかしいけど、とりあえずPositionの親子関係はできました
> 親子関係で相対的にPositionができるようになった

- EngineGL.Tests/Exec/NodeTest.cs
- EngineGL/Impl/Drawable/Shape2D/SolidBoxObject2D.cs
OpenGL4の件もあるのでいったん座標周りの作業はやめます
> SolidBoxObject2Dの中心が原点になるように

- EngineGL.Tests/Exec/GamrExecTest.cs
- EngineGL/Core/IComponent.cs
- EngineGL/Core/IObject.cs
- EngineGL/EngineGL.csproj
- EngineGL/Impl/Component.cs
- EngineGL/Impl/GameObject.cs
- EngineGL/Impl/Object.cs
- EngineGL/Impl/Objects/Camera.cs
- EngineGL/Impl/Scene.cs
- EngineGL/Impl/SceneManager.cs
- EngineGL/Serializations/Resulter/SerializeIgnoreAttribute.cs
> シリアライズのサンプルを書いた

- EngineGL/GraphicAdapter/Impl/OpenGL2/GraphicAdapter.cs
- EngineGL/Impl/Game.cs
- EngineGL/Impl/Objects/StaticCamera.cs
> 毎フレーム呼ばれるMatrixModeを減らした

- EngineGL.CITests/EngineGL.CITests.csproj
- EngineGL.CITests/Impl/Net/UdpSocketTests.cs
- EngineGL/Core/Net/ISocket.cs
- EngineGL/Core/Net/SocketState.cs
- EngineGL/EngineGL.csproj
- EngineGL/Impl/Net/UdpSocket.cs
- EngineGL/Impl/Net/UdpSocketBuilder.cs
> Udpクライアントを実装

- Doxyfile
- EngineGL.CITests/Impl/Net/UdpSocketTests.cs
- EngineGL/Core/Net/ITcpClientSocket.cs
- EngineGL/Core/Net/ITcpServerSocket.cs
- EngineGL/Core/Net/IUdpSocket.cs
- EngineGL/EngineGL.csproj
- EngineGL/Impl/Net/TcpClientSocket.cs
- EngineGL/Impl/Net/TcpServerSocket.cs
- EngineGL/Impl/Net/UdpSocket.cs
- EngineGL/Impl/Net/UdpSocketBuilder.cs
> TcpClientSocketを実装。

- EngineGL/Core/Net/ITcpServerSocket.cs
- EngineGL/Impl/Net/TcpClientSocket.cs
- EngineGL/Impl/Net/TcpServerSocket.cs
> TcpServerSocketを実装

- EngineGL/Impl/Game.cs
> エラーのダイアログが表示されるように

- EngineGL.Tests/EngineGL.Tests.csproj
- EngineGL.Tests/Exec/GameExecTest.cs
- EngineGL.Tests/Impl/GameTests.cs
- EngineGL/Core/IGame.cs
- EngineGL/Core/IScene.cs
- EngineGL/Impl/Game.cs
- EngineGL/Impl/Scene.cs
- EngineGL/Impl/SceneManager.cs
> Sceneの管理をGuidに変更

- EngineGL.Tests/Exec/PhysicsExecTests.cs
- EngineGL/GraphicAdapter/Impl/OpenGL2/VertexHandler.cs
- EngineGL/GraphicAdapter/Interface/IVertexHandler.cs
- EngineGL/Impl/DrawableComponents/Shape3D/SolidBoxObject3D.cs
- EngineGL/Impl/Game.cs
> 深層バッファとノーマルの実装

- EngineGL/Impl/Resource/ResourceManager.cs
> リソースをキャッシュ

- EngineGL.Tests/Exec/PhysicsExecTests.cs
- EngineGL.Tests/Exec/TestComponents/PlayerComponent.cs
- EngineGL.Tests/Exec/TestComponents/RotateComponent.cs
- EngineGL/Impl/Components/Physics/RigidBody3D.cs
- EngineGL/Impl/DrawableComponents/Shape2D/LineObject2D.cs
- EngineGL/Impl/DrawableComponents/Shape2D/SolidPolygonObject2D.cs
- EngineGL/Impl/DrawableComponents/Shape3D/SolidBoxObject3D.cs
- EngineGL/Impl/DrawableComponents/Shape3D/SolidPolygonObject3D.cs
- EngineGL/Structs/Math/Vec3.cs
> Polygon fix
